const config = {

  // constants    

  APPNAME: "LOAN CALCULATOR",
  //API_BASEPATH: "http://eventdawg.local3:8080/server/index.php/",

  WEEKS_PER_YEAR: 52.0,
  FORTNIGHTS_PER_YEAR: 26.0,
  MONTHS_PER_YEAR: 12,
  PRINCIPAL_AND_INTEREST: "principal and interest",
  INTEREST_ONLY: "interest only",

  PROPERTY_TYPE_LIVE_IN: 1,
  PROPERTY_TYPE_INVESTMENT: 2,

  DEFAULT_LOAN_AMOUNT: 350000,
  DEFAULT_INTEREST_RATE: 4.63,        // average variable interest rate australia 6-Jul-2020
  DEFAULT_LOAN_TERM: 30,
  DEFAULT_PROPERTY_VALUE: 430000,
  MAX_PROPERTY_VALUE: 500000000,
  MAX_LOAN: 5000000,
  MIN_LOAN: 1000,
  MIN_INTEREST: 0.26,
  MAX_INTEREST: 25,

  DEFAULT_MONTHLY_SALARY: 5000,
  DEFAULT_LUMP_SUM: 100000,
  DEFAULT_LUMP_SUM_YEAR: 5,
  DEFAULT_MAX_INCOME_AVAILABLE: 33.0, 

  FREQUENCY_ANNUAL: 1,
  FREQUENCY_MONTHLY: 2,
  FREQUENCY_FORTNIGHTLY: 3,
  FREQUENCY_WEEKLY: 4,

  FREQUENCY_NAME: ["", "annual", "monthly", "fortnightly", "weekly"],   

  DEFAULT_FIXED_PORTION_PERCENTAGE: 50,
  DEFAULT_FIXED_PERIOD_YEARS: 3,
  DEFAULT_FIXED_INTEREST_RATE: 2.56,      // average fixed interest rate australia 6-Jul-2020

  // CANVAS_WIDTH: 295,
  // CANVAS_HEIGHT: 190,

  CHART_WIDTH: 500,
  CHART_HEIGHT: 300,

  DEFAULT_EXTRA_REPAYMENT: 250,
  DEFAULT_EXTRA_REPAYMENT_START: 5,

  // CHART_LINE1_STROKE_COLOR: "rgba(26,153,235,1)",
  // CHART_LINE2_STROKE_COLOR: "rgba(204,225,26,1)",

  CHART_LINE1_STROKE_COLOR: "#8884d8",
  CHART_LINE2_STROKE_COLOR: "#82ca9d",

  SERIES_FILL_COLOR1: "rgba(26,153,235,0.2)",
  SERIES_FILL_COLOR2: "rgba(204,225,26,0.2)",

  KEY_DEL: 46,
  KEY_BACKSPACE: 8,
  KEY_LEFT: 37,
  KEY_UP: 38,
  KEY_RIGHT: 39,
  KEY_DOWN: 40,
  KEY_ENTER: 13,
  KEY_TAB: 9,
  KEY_ESCAPE: 27,

  CURRENCY_SYMBOL: "$",

  //task_count: 0,
}

export default config